<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <AssemblyName>Cineleaf</AssemblyName>
    <RootNamespace>Cineleaf.Windows</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>0.3.0-beta.1</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <PublishReadyToRun>true</PublishReadyToRun>
    <PublishTrimmed>false</PublishTrimmed>
    <DebugType>embedded</DebugType>
    <ApplicationIcon>Assets\Cineleaf.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Cineleaf.Windows.Core\Cineleaf.Windows.Core.csproj" />
    <ProjectReference Include="..\Cineleaf.Windows.Media\Cineleaf.Windows.Media.csproj" />
  </ItemGroup>
</Project>
